---
- hosts: all
  become: true
  vars:
    sudoGroup: "{{ 'sudo' if ansible_distribution == 'Ubuntu' else 'wheel' }}"

  tasks:
  - name: Add user to remote hosts
    user: name=ansible-user groups = " {{ sudoGroup }} "  shell=/bin/bash

  - name: Add SSH keys to remote hosts
    authorized_key: user=ansible-user key= " {{ lookup('file', '../files/id_rsa.pub') }} "
