---
- name: Install zabbix_agent
  hosts: servers
  become: true
  tasks:

  - name: Download zabbix repo
    get_url:
      url: https://repo.zabbix.com/zabbix/6.0/ubuntu/pool/main/z/zabbix-release/zabbix-release_6.0-4+ubuntu20.04_all.deb
      dest: /var/tmp/

  - name: Install zabbix repo
    apt:
      deb: /var/tmp/zabbix-release_6.0-4+ubuntu20.04_all.deb

  - name: Update
    apt:
      update_cache: yes

  - name: Install zabbix agent
    apt:
      name: zabbix-agent

  - name: Replace Server
    ansible.builtin.lineinfile:
      path: /etc/zabbix/zabbix_agentd.conf
      regexp: '^Server='
      line: Server=127.0.0.1,10.129.0.38

  - name: Replace Hostname
    ansible.builtin.lineinfile:
      path: /etc/zabbix/zabbix_agentd.conf
      regexp: '^Hostname='
      line: Hostname={{ ansible_hostname}}
      backup: true

  - name: Enable zabbix-agent
    systemd:
      name: zabbix-agent
      state: restarted
      enabled: yes
